workflows:
  build-apk:
    name: Build APK
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
