name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Make sure this matches the version you’re using

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release  # Change to --debug if needed

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: shadgpt-apk
        path: build/app/outputs/flutter-apk/app-release.apk  # Make sure this path is correct based on your project
